### ISSUE TITLE
double tab nougat lg g2

### ISSUE THREAD

**Issue by gcpmendez** [GalaticStryder/kernel_lge_msm8974#6]

**Comment by GalaticStryder** [comment]
Double tap to wake is sysfs controlled and built-in the lge_touch_core driver.
Here's the path: /sys/devices/virtual/input/lge_touch/touch_gesture
All drivers are the same as stock LG drivers with some misc fixes for AOSP/CM, the ROM developer just needs to add support for them by pointing those "files".
This means this inode is not Android sensitive, it doesn't care about its version if the frameworks to write 1 or 0 to the "file" is there.
Could add some more thoughts on why you opened this issue? It seems to work fine on my personal CM14 builds.
Thanks.

**Comment by GalaticStryder** [comment]
That's how we handle it in AOSPA: https://github.com/AOSPA/android_device_qcom_common/blob/marshmallow-caf/power/power-feature-default.c#L40
The 'sysfs_write' will write 1 or 0 if the switcher is enabled or disabled.

**Comment by gcpmendez** [comment]
Double tab to sleep?

**Comment by GalaticStryder** [comment]
@gcpmendez Most AOSP forks use their own frameworks to allow double tapping to sleep, making it a Kernel feature will only cause race conditions and more work on the mdss panel listeners. I'd recommend you to use the sweep to sleep feature for that matter if your ROM doesn't have the double tap to sleep.
