### ISSUE TITLE
Autorotation problem model VS980 

### ISSUE THREAD

**Issue by diegorosales994** [GalaticStryder/kernel_lge_msm8974#7]
I have used one of the lastest realizes of lamda kernel for this model, specifically Mashmallow N7 and the rotation go reverse of my device state, i don't  like to use my device with this problem

**Comment by GalaticStryder** [comment]
This is not Kernel related, it's indeed a Kernel sensor bug or hardware or even at software level. I'll close this BUG for now, please upgrade to latest builds and reply at XDA thread.
